name: Deploy My Static Site to Walrus with Provenance

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies in temporary directory and Build Explorer
        run: |
          cd ./src/explorer
          npm install -g pnpm
          pnpm install
          npm run build
          cp -r ./dist ../../dist
          cp ./site.config.json ../../site.config.json

      - name: Deploy to Walrus Sites
        uses: zktx-io/walrus-sites-provenance@v0.4.1
        env:
          ED25519_PRIVATE_KEY: ${{ secrets.ED25519_PRIVATE_KEY }}